import type { SymbolCategory, UnicodeStyleDefinition } from "@/lib/custom-text/types";

const UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const LOWER = "abcdefghijklmnopqrstuvwxyz";
const NUMBERS = "0123456789";

function range(start: number, count: number) {
  return Array.from({ length: count }, (_, index) =>
    String.fromCodePoint(start + index)
  );
}

export const SOURCE_ALPHABETS = {
  upper: UPPER.split(""),
  lower: LOWER.split(""),
  numbers: NUMBERS.split(""),
} as const;

const SMALL_CAPS: Record<string, string> = {
  a: "ᴀ",
  b: "ʙ",
  c: "ᴄ",
  d: "ᴅ",
  e: "ᴇ",
  f: "ꜰ",
  g: "ɢ",
  h: "ʜ",
  i: "ɪ",
  j: "ᴊ",
  k: "ᴋ",
  l: "ʟ",
  m: "ᴍ",
  n: "ɴ",
  o: "ᴏ",
  p: "ᴘ",
  q: "ǫ",
  r: "ʀ",
  s: "ꜱ",
  t: "ᴛ",
  u: "ᴜ",
  v: "ᴠ",
  w: "ᴡ",
  x: "x",
  y: "ʏ",
  z: "ᴢ",
};

const FULLWIDTH: Record<string, string> = {
  " ": "　",
  "!": "！",
  "?": "？",
  ".": "．",
  ",": "，",
  "-": "－",
  "_": "＿",
  "/": "／",
  "@": "＠",
  "#": "＃",
  "&": "＆",
};

const SCRIPT_UPPER = [
  "𝒜",
  "ℬ",
  "𝒞",
  "𝒟",
  "ℰ",
  "ℱ",
  "𝒢",
  "ℋ",
  "ℐ",
  "𝒥",
  "𝒦",
  "ℒ",
  "ℳ",
  "𝒩",
  "𝒪",
  "𝒫",
  "𝒬",
  "ℛ",
  "𝒮",
  "𝒯",
  "𝒰",
  "𝒱",
  "𝒲",
  "𝒳",
  "𝒴",
  "𝒵",
] as const;

const SCRIPT_LOWER = [
  "𝒶",
  "𝒷",
  "𝒸",
  "𝒹",
  "ℯ",
  "𝒻",
  "ℊ",
  "𝒽",
  "𝒾",
  "𝒿",
  "𝓀",
  "𝓁",
  "𝓂",
  "𝓃",
  "ℴ",
  "𝓅",
  "𝓆",
  "𝓇",
  "𝓈",
  "𝓉",
  "𝓊",
  "𝓋",
  "𝓌",
  "𝓍",
  "𝓎",
  "𝓏",
] as const;

export const UNICODE_STYLES: readonly UnicodeStyleDefinition[] = [
  {
    id: "msy-bold",
    name: "MSY Bold",
    description: "Forte, limpo e seguro para bios.",
    level: "stable",
    mobileSafe: true,
    transform: {
      upper: range(0x1d400, 26),
      lower: range(0x1d41a, 26),
      numbers: range(0x1d7ce, 10),
    },
  },
  {
    id: "msy-serif",
    name: "MSY Serif",
    description: "Elegante para nomes e frases curtas.",
    level: "stable",
    mobileSafe: true,
    transform: {
      upper: range(0x1d434, 26),
      lower: range(0x1d44e, 26),
    },
  },
  {
    id: "mono",
    name: "Mono",
    description: "Visual técnico para Discord e status.",
    level: "stable",
    mobileSafe: true,
    transform: {
      upper: range(0x1d670, 26),
      lower: range(0x1d68a, 26),
      numbers: range(0x1d7f6, 10),
    },
  },
  {
    id: "small-caps",
    name: "Small Caps",
    description: "Compacto e muito legível.",
    level: "stable",
    mobileSafe: true,
    replacements: SMALL_CAPS,
  },
  {
    id: "circled",
    name: "Circled",
    description: "Bom para nicknames curtos.",
    level: "stable",
    mobileSafe: true,
    transform: {
      upper: range(0x24b6, 26),
      lower: range(0x24d0, 26),
      numbers: ["⓪", "①", "②", "③", "④", "⑤", "⑥", "⑦", "⑧", "⑨"],
    },
  },
  {
    id: "fullwidth",
    name: "Aesthetic Wide",
    description: "Espaçado, limpo e compatível.",
    level: "stable",
    mobileSafe: true,
    transform: {
      upper: range(0xff21, 26),
      lower: range(0xff41, 26),
      numbers: range(0xff10, 10),
    },
    replacements: FULLWIDTH,
  },
  {
    id: "masayoshi-signature",
    name: "Masayoshi Signature",
    description: "Assinatura escura com presença MSY.",
    level: "masayoshi",
    mobileSafe: true,
    premium: true,
    prefix: "「 ",
    suffix: " 」",
    transform: {
      upper: range(0x1d400, 26),
      lower: range(0x1d41a, 26),
      numbers: range(0x1d7ce, 10),
    },
  },
  {
    id: "bio-clean",
    name: "Bio Clean",
    description: "Linha pronta para bio minimalista.",
    level: "masayoshi",
    mobileSafe: true,
    prefix: "━━ ",
    suffix: " ━━",
    transform: {
      upper: range(0x1d670, 26),
      lower: range(0x1d68a, 26),
      numbers: range(0x1d7f6, 10),
    },
  },
  {
    id: "dark-rune",
    name: "Dark Rune",
    description: "Mais agressivo, ideal para frases curtas.",
    level: "experimental",
    mobileSafe: false,
    premium: true,
    prefix: "⛧ ",
    suffix: " ⛧",
    replacements: {
      a: "ᚪ",
      b: "ᛒ",
      c: "ᚳ",
      d: "ᛞ",
      e: "ᛖ",
      f: "ᚠ",
      g: "ᚷ",
      h: "ᚺ",
      i: "ᛁ",
      j: "ᛃ",
      k: "ᚴ",
      l: "ᛚ",
      m: "ᛗ",
      n: "ᚾ",
      o: "ᛟ",
      p: "ᛈ",
      r: "ᚱ",
      s: "ᛋ",
      t: "ᛏ",
      u: "ᚢ",
      v: "ᚡ",
      w: "ᚹ",
      x: "ᛪ",
      y: "ᛦ",
      z: "ᛉ",
    },
  },
  {
    id: "script",
    name: "Script",
    description: "Cursivo bonito, pode variar por aparelho.",
    level: "experimental",
    mobileSafe: false,
    transform: {
      upper: SCRIPT_UPPER,
      lower: SCRIPT_LOWER,
    },
  },
  {
    id: "squared",
    name: "Squared",
    description: "Blocos visuais para nomes curtos.",
    level: "experimental",
    mobileSafe: false,
    transform: {
      upper: range(0x1f130, 26),
    },
  },
  {
    id: "shadow",
    name: "Shadow",
    description: "Estilo decorativo com marcação combinante.",
    level: "experimental",
    mobileSafe: false,
    separator: "̷",
  },
] as const;

export const SYMBOL_CATEGORIES: readonly SymbolCategory[] = [
  {
    id: "decorative",
    name: "Decorativos",
    description: "Para destacar nomes, títulos e status.",
    symbols: ["✦", "✧", "✶", "✷", "✹", "✺", "✦̲", "❖", "◆", "◇", "◈", "⬩"],
  },
  {
    id: "minimal",
    name: "Minimalistas",
    description: "Símbolos discretos para bio clean.",
    symbols: ["·", "•", "∙", "⋅", "∘", "◦", "＿", "￣", "⌁", "⌇", "⌞", "⌝"],
  },
  {
    id: "japanese",
    name: "Japoneses",
    description: "Aesthetic inspirado em kaomoji e cultura visual japonesa.",
    symbols: ["々", "〆", "〄", "〘", "〙", "『", "』", "「", "」", "ー", "ヾ", "ツ"],
  },
  {
    id: "dark",
    name: "Dark",
    description: "Visual sombrio para nicknames e frases.",
    symbols: ["†", "‡", "⛧", "☽", "☾", "✞", "✟", "♱", "☠", "☣", "☢", "⟁"],
  },
  {
    id: "social",
    name: "Sociais",
    description: "Indicadores úteis para perfis.",
    symbols: ["@", "#", "♡", "↳", "⌕", "⌁", "✉", "☎", "⌂", "⌘", "◌", "◎"],
  },
  {
    id: "separators",
    name: "Separadores",
    description: "Linhas e divisores para bios.",
    symbols: ["━━", "──", "────", "━━━━", "╌╌", "═", "════", "⟡────⟡", "･ﾟ: *", "୨୧"],
  },
  {
    id: "stars",
    name: "Estrelas",
    description: "Brilho e destaque aesthetic.",
    symbols: ["★", "☆", "✩", "✪", "✫", "✬", "✭", "✮", "✯", "✰", "⋆", "⁺₊⋆"],
  },
  {
    id: "hearts",
    name: "Corações",
    description: "Bio, status e nomes suaves.",
    symbols: ["♥", "♡", "❤", "❥", "❦", "❧", "ღ", "۵", "ও", "ᥫ᭡", "ෆ", "ꨄ"],
  },
  {
    id: "arrows",
    name: "Setas",
    description: "Direção, links e chamadas.",
    symbols: ["→", "←", "↳", "↲", "↱", "↴", "⇢", "⇠", "➜", "➤", "➳", "⟶"],
  },
  {
    id: "bio",
    name: "Bio",
    description: "Decorações prontas para redes sociais.",
    symbols: ["「」", "『』", "【】", "✦ bio ✦", "♡︎", "𖤐", "⟡", "꒰ ꒱", "₊˚", "˖ ࣪"],
  },
  {
    id: "special",
    name: "Especiais",
    description: "Caracteres raros para composições.",
    symbols: ["ℵ", "℧", "ℭ", "ℌ", "ℑ", "ℜ", "⌬", "⌖", "⎊", "⟁", "⧉", "⫷"],
  },
  {
    id: "premium",
    name: "Premium",
    description: "Pacote MSY para combinações marcantes.",
    premium: true,
    symbols: ["♛", "♕", "⟡", "⟢", "⟣", "𖤐", "𖣔", "𖣘", "𖦹", "𖧷", "𖨆", "𖠌"],
  },
] as const;
